# Generated by Django 3.2.4 on 2021-06-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0002_overtime_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtime',
            name='hour',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
